
-- FIND THE ITEM WITH MINIMUM WEIGHT
SELECT ITEM_NO,ITEM_DISCRIPTION,ITEM_WEIGHT,
MIN(ITEM_WEIGHT)
FROM ITEMS;

-- FIND THE DIFFERENT WAREHOUSES IN "PUNE"
SELECT W_NAME , c.city
FROM warehouse w
inner join cities c
on 
w.W_LOCATION = c.CITY_ID
where c.city = 'pune';

-- FIND THE DETAILS OF ITEM ORDERED BY A CUSTOMER "VIJAY" 
SELECT O.O_NO,I.ITEM_NO,O.O_DATE 'DATE',I.ITEM_DISCRIPTION,I.ITEM_WEIGHT,I.ITEM_COST
FROM ORDERS O
INNER JOIN CUSTOMER C
ON O.O_BY = C.C_NO
INNER JOIN ORDER_SUMMERY OS
ON OS.O_NO = O.O_NO
INNER JOIN ITEMS I
ON I.ITEM_NO = OS.ITEM_NO
WHERE C.C_NAME = 'VIJAY';

-- Find a Warehouse which has maximum stores.
SELECT 
COUNT(C.CITY)
FROM WAREHOUSE W
INNER JOIN STORES S
ON 
S.S_LOCATION_CITY = W.W_LOCATION
INNER JOIN CITIES C
ON 
W.W_LOCATION = C.CITY
WHERE C.CITY = 'PUNE';

